apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  links: 
    - url: ${{ parameters.repoUrl | dump }}
      type: website
      title: Website
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
